### ISSUE TITLE
install problem of permissions

### ISSUE THREAD

**Issue by ghost** [forkbb/forkbb#31]
I've followed every installation steps to setup forkbb, unfortunately i came across this.

```
PHP E_WARNING: chmod(): Operation not permitted in .../app/Core/Log.php:[158]

Trace:

-(-): ForkBB\Core\ErrorHandler->errorHandler(integer, string, string, integer)
.../app/Core/Log.php(87): ForkBB\Core\Log->initResource()
.../app/Core/Log.php(262): ForkBB\Core\Log->log(string, string, array(2))
.../app/Core/ErrorHandler.php(244): ForkBB\Core\Log->error(string, array(2))
.../app/Core/ErrorHandler.php(148): ForkBB\Core\ErrorHandler->log(array(6))
-(-): ForkBB\Core\ErrorHandler->exceptionHandler(object{Error})
```

I have every extensions required to run forkbb, i have chmodded the directory i have the entire forkbb in, but nothing.

php ver = 8.2

**Comment by MioVisman** [comment]
Check on whose behalf the folders inside forkbb were created. Specifically /app/log/. The owner must be the same user on whose behalf php is running.
If you used composer, then there could be another user there.

Engine installation topic https://forkbb.ru/topic/28/ustanovka-installation (in Russian, use Google Translator).

**Comment by MioVisman** [comment]
I have now tested the installation https://github.com/forkbb/forkbb/releases/tag/0.0078.1, but on Windows 7 (there are no access problems on it). I still haven't installed Linux on my home computer.

**Comment by ghost** [comment]
Thanks for the fast reply, ill test it out when i have time. ill report in any issues if i come across one.

**Comment by ghost** [comment]
nope, everything is still how it is.
```
PHP E_WARNING: chmod(): Operation not permitted in .../app/Core/Log.php:[158]

Trace:

-(-): ForkBB\Core\ErrorHandler->errorHandler(integer, string, string, integer)
.../app/Core/Log.php(87): ForkBB\Core\Log->initResource()
.../app/Core/Log.php(262): ForkBB\Core\Log->log(string, string, array(2))
.../app/Core/ErrorHandler.php(204): ForkBB\Core\Log->error(string, array(2))
.../app/Core/ErrorHandler.php(147): ForkBB\Core\ErrorHandler->log(array(6))
-(-): ForkBB\Core\ErrorHandler->exceptionHandler(object{Error})
```

**Comment by MioVisman** [comment]
Are there any errors in the server error file (for example, error.log)? Because this warning ( chmod(): Operation not permitted) is a consequence of another error that the engine cannot write to the log.

Try editing the /app/bootstrap.php file to see the original error:
delete string
```
$errorHandler = new ErrorHandler();
```
and
delete string
```
$errorHandler->setContainer($c);
```

But still, the options for the occurrence of a warning (chmod(): Operation not permitted) are as follows:

1. The /app/log/ folder has a different owner than the owner of the php process.
2. To increase security, the server administrator has prohibited changing access rights to folders/files using the chmod() command.
3. The engine was installed incorrectly, as a result the /app/log/ folder was not found and could not be created for some reason.

Change the /app/Core/Log.php file:
reaplace
```
            if (! \chmod($dir, 0755)) {
                throw new RuntimeException("Error changing the access mode to '{$dir}' directory");
            }
```
to
```
exit(var_dump($dir));
            if (! \chmod($dir, 0755)) {
                throw new RuntimeException("Error changing the access mode to '{$dir}' directory");
            }
```
After this, the path to the log folder should be displayed.
Check whether the log folder exists in this path and what rights it has for the owner of the process under which php is running when logging in from the browser.

**Comment by ghost** [comment]
> Are there any errors in the server error file (for example, error.log)? Because this warning ( chmod(): Operation not permitted) is a consequence of another error that the engine cannot write to the log.

Nope nothing in /app/log/, unless if you are speaking about apache2 logs, then it is the same as what i wrote on here.

`Fatal error: Uncaught Error: Cannot instantiate interface Psr\SimpleCache\CacheException in /var/www/html/forkbb/app/Core/Cache/FileCache.php:40 Stack trace: #0 /var/www/html/forkbb/app/Core/Container.php(126): ForkBB\Core\Cache\FileCache->__construct() #1 /var/www/html/forkbb/app/Core/Lang.php(85): ForkBB\Core\Container->__get() #2 /var/www/html/forkbb/app/Core/Container.php(126): ForkBB\Core\Lang->__construct() #3 /var/www/html/forkbb/app/Controllers/Install.php(29): ForkBB\Core\Container->__get() #4 /var/www/html/forkbb/app/Core/Container.php(122): ForkBB\Controllers\Install->routing() #5 /var/www/html/forkbb/app/bootstrap.php(77): ForkBB\Core\Container->__get() #6 /var/www/html/forkbb/index.php(14): require('...') #7 {main} thrown in /var/www/html/forkbb/app/Core/Cache/FileCache.php on line 40`

this is the current error i have now after applying changes.

**Comment by MioVisman** [comment]
How did you copy the engine files to your server?
Psr\SimpleCache is missing, which should automatically be connected through the composer autoloader.
It is in the vendor folder https://github.com/forkbb/forkbb/tree/master/vendor/psr/simple-cache and in the archives with releases https://github.com/forkbb/forkbb/releases it is also there, since release archives are made as completely independent installers that do not require running composer for installation/updating, that is, they are designed for shared hosting.

**Comment by ghost** [comment]
>How did you copy the engine files to your server?

I used github first but then removed the github copy and used release file to put it in the directory.

>Psr\SimpleCache is missing

I do have simplecache which is just named "simple-cache".

**Comment by MioVisman** [comment]
The easiest way to install:
1. Determine the folder in which the forum should be installed on the server and copy in it in any way available to you all the folders (with their contents) and files from the latest audit https://github.com/Forkbb/ForkbB/releases/tag/0.0078.1 In the screenshot below:
![archive](https://github.com/forkbb/forkbb/assets/5917956/80b5ee1d-ad74-4864-a9a4-b1aace8a936d)
2. After that, in this server folder, change the file names: `.dist.htaccess` -> `.htaccess` and `index.dist.php` ->` index.php`
3. Open your site in the browser, the installation page should appear. Make installation - a page with a list of forums appears.
P.S. The second point for the Apache. Do you have Apache on the server?

**Comment by ghost** [comment]
Followed the instructions.

I removed old file and used file that you linked me, I have all of the folders and i renamed the files.

First results:

```
PHP E_WARNING: chmod(): Operation not permitted in .../app/Core/Log.php:[158]

Trace:

-(-): ForkBB\Core\ErrorHandler->errorHandler(integer, string, string, integer)
.../app/Core/Log.php(87): ForkBB\Core\Log->initResource()
.../app/Core/Log.php(262): ForkBB\Core\Log->log(string, string, array(2))
.../app/Core/ErrorHandler.php(204): ForkBB\Core\Log->error(string, array(2))
.../app/Core/ErrorHandler.php(147): ForkBB\Core\ErrorHandler->log(array(6))
-(-): ForkBB\Core\ErrorHandler->exceptionHandler(object{Error})
```

I do have Apache on the server, nothing else.

**Comment by MioVisman** [comment]
If there is nothing confidential on your site, then give me (send an email to the address mio.visman@gmail.com) access to the control panel your site: the address of entry into the control panel, login, password.

**Comment by ghost** [comment]
> If there is nothing confidential on your site, then give me (send an email to the address [mio.visman@gmail.com](mailto:mio.visman@gmail.com)) access to the control panel your site: the address of entry into the control panel, login, password.

localhost, sorry! and my bad that i forgot to say.
